name: {{PROJECT_NAME}}
channels:
    - conda-forge
    - nodefaults
dependencies:
    - python={{LANGUAGE_VERSION}}
    - pip
    - pip:
          - -r requirements.txt
          - -r .devcontainer/requirements_dev.txt
